app = "elysiango-mutawwif-api"
primary_region = "sin"

[env]
  PORT = "3020"
  NODE_ENV = "production"

[[services]]
  internal_port = 3020
  protocol = "tcp"

  [[services.ports]]
    port = 80

  [[services.ports]]
    port = 443
